# Data Cleaning and Preparation of a Hashed Dataset

### Step 1: Mount Google Drive

Run the following cell to mount your Google Drive. You will be prompted to authorize this notebook to access your Drive files. Follow the instructions to complete the authorization.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Step 2: Locate your CSV file and load it with pandas

After your Drive is mounted, you can find the path to your CSV file. Google Drive files will typically be located under `/content/drive/MyDrive/`.

For example, if your file `my_data.csv` is directly in your 'My Drive' folder, the path would be `/content/drive/MyDrive/my_data.csv`.

Replace `'YOUR_CSV_FILE_PATH'` in the code below with the actual path to your CSV file. Then, the code will load it into a pandas DataFrame and display the first 5 rows.

In [ ]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/NZ/University of Waikato/Māori Data Findability Project/stage2_colab/Datasets/4_waikato_full_dataset_16777_hased.csv'

try:
    df = pd.read_csv(csv_file_path)
    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    print("First 5 rows of the DataFrame:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred while loading the CSV file: {e}")

Successfully loaded '/content/drive/MyDrive/NZ/University of Waikato/Māori Data Findability Project/stage2_colab/Datasets/4_waikato_full_dataset_16777_hased.csv' into a DataFrame.
First 5 rows of the DataFrame:

,record_id,title,authors,year,subjects,abstract,url,text,record_id_hash
0,NaN,Characterizing porous microaggregates and soil...,"Huang, Doreen Yu-Tuan",2021,Science & Technology,Allophanic tephra-derived soils can sequester ...,NaN,Characterizing porous microaggregates and soil...,fefa3d488de2a37e6bac3bb97033e389a7f3274f1626b8...
1,NaN,Sexual Desire in Women Presenting for Antiandr...,"Conaglen, Helen M.",2003,antiandrogen therapy,Women presenting with hirsuties/polycystic ova...,NaN,Sexual Desire in Women Presenting for Antiandr...,7e6086aed791d4d7c9e56b862f4a36aaaf39e6f0de8d15...
2,NaN,Aluminium content in near-shore sediments of L...,"Tempero, Grant Wayne",2019,NaN,The application of alum (aluminium sulphate) i...,NaN,Aluminium content in near-shore sediments of L...,b9b3e816cb791407640fa08a033bc2b7b09c4fb9a7438c...
3,NaN,Introduction,"Houlahan, Mark",2019,NaN,"When Dr Johnson, the 18• century critic, was a...",NaN,"Introduction When Dr Johnson, the 18• century ...",4c3bde78419fd2dcf4944c39180e42d828f641c5ac05a8...
4,NaN,Is peer review in academic publishing still wo...,"Jackson, Liz",2018,Peer review,Peer review is central to academic publishing....,NaN,Is peer review in academic publishing still wo...,85ee578de741354f56d5fae8970ad2c89319d64b6efdce...

### Re-evaluating Data Information and Descriptive Statistics for the Hashed Dataset

Now that we've loaded the hashed dataset, let's look at its structure, data types, and non-null counts using `df.info()`, and descriptive statistics for numerical columns using `df.describe()`.

In [ ]:
print('--- DataFrame Information (Hashed Dataset) ---')
df.info()

--- DataFrame Information (Hashed Dataset) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16777 entries, 0 to 16776
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   record_id       0 non-null      float64
 1   title           16777 non-null  object
 2   authors         16634 non-null  object
 3   year            16670 non-null  object
 4   subjects        11950 non-null  object
 5   abstract        16678 non-null  object
 6   url             0 non-null      float64
 7   text            16777 non-null  object
 8   record_id_hash  16777 non-null  object
dtypes: float64(2), object(7)
memory usage: 1.2+ MB

In [ ]:
print('\n--- Descriptive Statistics for Numerical Columns (Hashed Dataset) ---')
display(df.describe())

--- Descriptive Statistics for Numerical Columns (Hashed Dataset) ---

       record_id  url
count        0.0  0.0
mean         NaN  NaN
std          NaN  NaN
min          NaN  NaN
25%          NaN  NaN
50%          NaN  NaN
75%          NaN  NaN
max          NaN  NaN

### Step 4: Data Cleaning - Handling Empty Columns in Hashed Dataset

As confirmed by `df.info()` and `df.describe()` for the hashed dataset, the 'record_id' and 'url' columns contain no data. We will drop these columns from the DataFrame to focus on relevant information.

In [ ]:
print('--- Dropping empty columns (record_id, url) from Hashed Dataset ---')
df_cleaned = df.drop(columns=['record_id', 'url'])
print('DataFrame after dropping columns:')
df_cleaned.info()

--- Dropping empty columns (record_id, url) from Hashed Dataset ---
DataFrame after dropping columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16777 entries, 0 to 16776
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           16777 non-null  object
 1   authors         16634 non-null  object
 2   year            16670 non-null  object
 3   subjects        11950 non-null  object
 4   abstract        16678 non-null  object
 5   text            16777 non-null  object
 6   record_id_hash  16777 non-null  object
dtypes: object(7)
memory usage: 917.6+ KB

### Step 5: Initial Exploration of Object Columns in Hashed Dataset

Now that we've cleaned the DataFrame, let's look at the unique values and their counts for some of the key object-type columns to understand their distribution and potential for further analysis. This will include 'year', 'authors', 'subjects', and the new 'record_id_hash' column.

In [ ]:
print('\n--- Unique values and counts for \'year\' (top 20) ---')
display(df_cleaned['year'].value_counts().head(20))

print('\n--- Unique values and counts for \'authors\' (top 20) ---')
display(df_cleaned['authors'].value_counts().head(20))

--- Unique values and counts for 'year' (top 20) ---

year
2011    947
2010    904
2013    869
2012    868
2016    797
2017    778
2008    667
2015    648
2009    636
2018    602
2019    589
2007    544
2020    531
2014    501
2021    493
2022    436
2006    417
2024    364
2025    345
2023    301
Name: count, dtype: int64

--- Unique values and counts for 'authors' (top 20) ---

authors
Hart, Philip               160
Lowe, David J.             118
Kalnins, Ernie G.           74
Hicks, Brendan J.           72
Pratt, Douglas              59
Gibson, John                58
Cunningham, Sally Jo        52
Hinze, Annika               50
Witten, Ian H.              45
Peters, Michael A.          45
Nikora, Linda Waimarie      44
Weijers, Dan M.             43
Maxwell, Te Kahautu         43
Chevalier-Watts, Juliet     40
Legg, Catherine             40
Frank, Eibe                 39
Bainbridge, David           39
Holmes, Mark J.             37
Broughan, Kevin A.          36
Aporosa, S. 'Apo'           36
Name: count, dtype: int64

In [ ]:
print('\n--- Unique values and counts for \'subjects\' (top 20) ---')
display(df_cleaned['subjects'].value_counts().head(20))

--- Unique values and counts for 'subjects' (top 20) ---

subjects
computer science        876
Science & Technology    470
New Zealand             230
Maori                   140
Social Sciences         100
biology                  98
education                97
book review              89
chemistry                75
mathematics              71
Mathematics              56
Antarctica               41
Machine learning         41
Māori                    37
China                    31
accounting               27
law                      24
psychology               24
engineering              21
religion                 17
Name: count, dtype: int64

In [ ]:
print('\n--- Number of unique values for \'record_id_hash\' ---')
print(df_cleaned['record_id_hash'].nunique())

print('\n--- Checking for duplicate \'record_id_hash\' entries ---')
print(df_cleaned.duplicated(subset=['record_id_hash']).sum())

--- Number of unique values for 'record_id_hash' ---
16777

--- Checking for duplicate 'record_id_hash' entries ---
0

### Step 6: Further Data Cleaning - Handling Missing Values and Duplicates in Key Columns

Let's investigate the 'authors', 'abstract', and 'year' columns for missing values and duplicates to ensure data quality. We'll start by checking the count of null values in each of these columns.

In [ ]:
print('\n--- Missing values in \'authors\', \'abstract\', and \'year\' ---')
print(df_cleaned[['authors', 'abstract', 'year']].isnull().sum())

--- Missing values in 'authors', 'abstract', and 'year' ---
authors     143
abstract     99
year        107
dtype: int64

Now, let's examine potential duplicate entries. While duplicate authors or years are expected, a combination of title, abstract, and authors could indicate a duplicate record. We will check for duplicates based on these columns, excluding the unique `record_id_hash`.

In [ ]:
print('\n--- Checking for duplicate entries based on \'title\', \'abstract\', \'authors\', and \'year\' ---')
duplicate_entries = df_cleaned[df_cleaned.duplicated(subset=['title', 'abstract', 'authors', 'year'], keep=False)]

if not duplicate_entries.empty:
    print(f"Found {len(duplicate_entries)} potential duplicate entries.")
    display(duplicate_entries.sort_values(by=['title', 'year']).head())
else:
    print("No duplicate entries found based on 'title', 'abstract', 'authors', and 'year'.")

--- Checking for duplicate entries based on 'title', 'abstract', 'authors', and 'year' ---
No duplicate entries found based on 'title', 'abstract', 'authors', and 'year'.

### Step 7: Analyzing Records with Same Author and Abstract but Different Years

Let's investigate if there are instances where the 'authors' and 'abstract' are identical, but the 'year' of publication differs. This could indicate revised versions of a paper, pre-prints, or just separate publications by the same authors on a very similar topic. We will group by 'authors' and 'abstract' and then check for multiple unique years within these groups.

In [ ]:
print('\n--- Identifying records with same authors and abstract but different years ---')

# Group by 'authors' and 'abstract' and count unique years
year_variations = df_cleaned.groupby(['authors', 'abstract'])['year'].nunique().reset_index()
year_variations.rename(columns={'year': 'unique_years_count'}, inplace=True)

# Filter for groups where the number of unique years is greater than 1
multi_year_entries_summary = year_variations[year_variations['unique_years_count'] > 1]

if not multi_year_entries_summary.empty:
    print(f"Found {len(multi_year_entries_summary)} groups with the same authors and abstract but multiple publication years.")
    display(multi_year_entries_summary)

    # Display all examples, instead of just the head(3)
    print('\n--- Examples of all such records ---')
    for index, row in multi_year_entries_summary.iterrows():
        authors = row['authors']
        abstract = row['abstract']
        print(f"\nAuthors: {authors}\nAbstract: {abstract[:100]}...") # Truncate abstract for display
        display(df_cleaned[(df_cleaned['authors'] == authors) & (df_cleaned['abstract'] == abstract)].sort_values(by='year'))
else:
    print("No records found with the same authors and abstract but different years.")

--- Identifying records with same authors and abstract but different years ---
Found 18 groups with the same authors and abstract but multiple publication years.

,authors,abstract,unique_years_count
4622,"Frank, Eibe",Bagging is an ensemble learning method that ha...,2
4896,"Ghaleiha, Amin",Becoming a father is a major transition for me...,2
5341,"Groves, Lindsay",We report on the software development techniqu...,2
6451,"Holmes, Mark J.",Markov regime-switching analysis is used to co...,2
7668,"Khoo, Elaine G.L.",Developing online learning communities is a pr...,2
8882,"Lowe, David J.","New Zealand consists of a cluster of islands, ...",2
8899,"Lowe, David J.",Tephras are fragmentary materials that are bla...,2
10262,"Mohajerani, Sahar",In a previous paper we introduced the notion o...,2
10833,"Nichols, David M.",Open source communities have successfully deve...,2
10843,"Nichols, David M.",We describe a Web-based metadata quality tool ...,2
10952,"Nock, Sophie",Ko te whāinga matua o tēnei rangahau he whakak...,2
11786,"Plimmer, Beryl",This demonstration shows the tool we have deve...,2
11936,"Pratt, Douglas",The coming together of people of diverse relig...,2
13361,"Siebel, Wolfgang",The Acigöl rhyolite field erupted the most rec...,2
13881,"Stokes, Evelyn",A report providing a historical and geographic...,2
15162,"Walmsley, Timothy Gordon",Heat recovery from exhaust gas streams is appl...,2
15166,"Walmsley, Timothy Gordon",One method to reduce the energy consumption of...,2
15212,"Wang, Hongyu",Metaheuristic search algorithms are used to de...,2

--- Examples of all such records ---

Authors: Frank, Eibe
Abstract: Bagging is an ensemble learning method that has proved to be a useful tool in the arsenal of machine...

,title,authors,year,subjects,abstract,text,record_id_hash
11621,Improving on bagging with input smearing,"Frank, Eibe",2006,computer science,Bagging is an ensemble learning method that ha...,Improving on bagging with input smearing Baggi...,bcad3933ee79142f85313913024080676d7fdaf0db73a0...
11380,An Empirical Comparison of Exact Nearest Neigh...,"Frank, Eibe",2007,computer science,Bagging is an ensemble learning method that ha...,An Empirical Comparison of Exact Nearest Neigh...,fd42d27645ab3be23c072a5e182e6abb388d1bd69cd9da...

Authors: Ghaleiha, Amin
Abstract: Becoming a father is a major transition for men, and may be a source of happiness and fulfilment, as...

,title,authors,year,subjects,abstract,text,record_id_hash
9048,Fathers' Help Seeking and Support: The Importa...,"Ghaleiha, Amin",2024,NaN,Becoming a father is a major transition for me...,Fathers' Help Seeking and Support: The Importa...,f799d9041909764069b14197f1bff0560c6a12312d83cc...
15421,Fathers’ help-seeking and support: The importa...,"Ghaleiha, Amin",2024-03-25,Fatherhood,Becoming a father is a major transition for me...,Fathers’ help-seeking and support: The importa...,1f69151a14c9fb29894988c10cae211d997e1e37112a53...

Authors: Groves, Lindsay
Abstract: We report on the software development techniques used in the New Zealand software industry, paying p...

,title,authors,year,subjects,abstract,text,record_id_hash
15837,A survey of software requirements specificatio...,"Groves, Lindsay",1999-06,computer science,We report on the software development techniqu...,A survey of software requirements specificatio...,c1126e4a9234d4a674d63d50518d6410f5308b4384a1c0...
12580,A survey of software development practices in ...,"Groves, Lindsay",2000-04,survey,We report on the software development techniqu...,A survey of software development practices in ...,5a04ae713f5ac1ec27ec2063491edd450a7d971228e479...

Authors: Holmes, Mark J.
Abstract: Markov regime-switching analysis is used to consider the relationship between business confidence an...

,title,authors,year,subjects,abstract,text,record_id_hash
5439,Business confidence and cyclical turning point...,"Holmes, Mark J.",2007-09,business confidence,Markov regime-switching analysis is used to co...,Business confidence and cyclical turning point...,201cce37ffe7032fad148947beb2b882dee08797ea9984...
13146,Business confidence and cyclical turning point...,"Holmes, Mark J.",2010,New Zealand,Markov regime-switching analysis is used to co...,Business confidence and cyclical turning point...,d7a0e39a2d95abfa1d85a71589c8026d1bc9156c54aa42...

Authors: Khoo, Elaine G.L.
Abstract: Developing online learning communities is a promising pedagogical approach in online learning contex...

,title,authors,year,subjects,abstract,text,record_id_hash
4481,Evaluating an online learning community: Intel...,"Khoo, Elaine G.L.",2011,online teaching,Developing online learning communities is a pr...,Evaluating an online learning community: Intel...,2a9c3597cfbe758e59eba2348da7445f6288791bfed4f1...
6412,Evaluating an online learning community: Intel...,"Khoo, Elaine G.L.",2015,Online teaching,Developing online learning communities is a pr...,Evaluating an online learning community: Intel...,7f2be37944dfe5ed0dfaee5573ef35d13813d9ae94433c...

Authors: Lowe, David J.
Abstract: New Zealand consists of a cluster of islands, the three largest being North, South, and Stewart, in ...

,title,authors,year,subjects,abstract,text,record_id_hash
13970,Introduction to New Zealand,"Lowe, David J.",1994,NaN,"New Zealand consists of a cluster of islands, ...",Introduction to New Zealand New Zealand consis...,21b9b30d9a41d7fa3a7c78af19fcb59cd8a1970903cb74...
7517,Intra-conference and Post-conference Tour Guid...,"Lowe, David J.",1994-02-01,NaN,"New Zealand consists of a cluster of islands, ...",Intra-conference and Post-conference Tour Guid...,8af3e7178093a47826e8cdbdff6f05fc1bbfb6c9bf1f50...

Authors: Lowe, David J.
Abstract: Tephras are fragmentary materials that are blasted explosively into the air during volcanic eruption...

,title,authors,year,subjects,abstract,text,record_id_hash
15571,Far-flung markers,"Lowe, David J.",2008,NaN,Tephras are fragmentary materials that are bla...,Far-flung markers Tephras are fragmentary mate...,d52fd75756a6f010fcde85a574b645aae9ce196b8cee0a...
6027,Far-flown markers,"Lowe, David J.",2015,"tephras, tephrostratigraphy, tephrochronology,...",Tephras are fragmentary materials that are bla...,Far-flown markers Tephras are fragmentary mate...,71caf83655b3ac61f6c5ec3565764c79b2d9fac80e2d05...

Authors: Mohajerani, Sahar
Abstract: In a previous paper we introduced the notion of synthesis abstraction, which allows efficient compos...

,title,authors,year,subjects,abstract,text,record_id_hash
731,On the use of observation equivalence in synth...,"Mohajerani, Sahar",2011,computer science,In a previous paper we introduced the notion o...,On the use of observation equivalence in synth...,c86d7c5f5bc38b79488d961ac031cba272f2f87bc1d4c7...
15964,Three variations of observation equivalence pr...,"Mohajerani, Sahar",2011-01-26,computer science,In a previous paper we introduced the notion o...,Three variations of observation equivalence pr...,f1a6d0a058ccbab552a9567eb7830c4456d80d57cf9d2c...

Authors: Nichols, David M.
Abstract: Open source communities have successfully developed many pieces of software although most computer u...

,title,authors,year,subjects,abstract,text,record_id_hash
15950,Usability and open source software,"Nichols, David M.",2002-12-01,NaN,Open source communities have successfully deve...,Usability and open source software Open source...,77c65fbc4a5df4fe40fdc69a90bee37acc3eea592e31a0...
12915,The usability of open source software: analysi...,"Nichols, David M.",2006,computer science,Open source communities have successfully deve...,The usability of open source software: analysi...,536d6fad078577619eac0a8b1a16665937397a52740271...

Authors: Nichols, David M.
Abstract: We describe a Web-based metadata quality tool that provides statistical descriptions and visualisati...

,title,authors,year,subjects,abstract,text,record_id_hash
4314,A lightweight metadata quality tool,"Nichols, David M.",2008,computer science,We describe a Web-based metadata quality tool ...,A lightweight metadata quality tool We describ...,618091212551afb707a6cd1fdd1343d8103f96fb5ac9d1...
15918,A tool for metadata analysis,"Nichols, David M.",2008-02,measurement,We describe a Web-based metadata quality tool ...,A tool for metadata analysis We describe a Web...,81cc25e4dd2f8a0ebd7224fc98487ed53b56ac03e27843...

Authors: Nock, Sophie
Abstract: Ko te whāinga matua o tēnei rangahau he whakakaokao, he wetewete āno hoki i ngā whakahokinga kōrero ...

,title,authors,year,subjects,abstract,text,record_id_hash
8181,He pūrongo whakahokinga kōrero a te akomanga r...,"Nock, Sophie",2012-05,Reo Māori,Ko te whāinga matua o tēnei rangahau he whakak...,He pūrongo whakahokinga kōrero a te akomanga r...,581b67e67aa329dbc5c01eeead857bf439844473417e47...
12469,Ko ngā whakahokinga kōrero a te hunga uiui i r...,"Nock, Sophie",2017,Reo Māori,Ko te whāinga matua o tēnei rangahau he whakak...,Ko ngā whakahokinga kōrero a te hunga uiui i r...,d06505c6be7d73dff773eb3d02a32cdf7bb8a2992eed54...

Authors: Plimmer, Beryl
Abstract: This demonstration shows the tool we have developed for hand-sketching user interfaces. Our motivati...

,title,authors,year,subjects,abstract,text,record_id_hash
1700,FreeForm: Informal form design on a large inte...,"Plimmer, Beryl",2001,Sketching,This demonstration shows the tool we have deve...,FreeForm: Informal form design on a large inte...,5f7200db64960c77d69846d6205e2f92912b1543bfc7e4...
11155,Freeform: A Tool for Sketching Form Designs,"Plimmer, Beryl",2003,Sketching,This demonstration shows the tool we have deve...,Freeform: A Tool for Sketching Form Designs Th...,de1eaf88deff73f5adebcb8d89f34d98aa3271fc2996f3...

Authors: Pratt, Douglas
Abstract: The coming together of people of diverse religions to plan or reflect upon a common action or ventur...

,title,authors,year,subjects,abstract,text,record_id_hash
10260,Interreligious prayer: Prospects and parameters,"Pratt, Douglas",2006-10,religion,The coming together of people of diverse relig...,Interreligious prayer: Prospects and parameter...,2a8d930d4ddc5bb6f1a766d20f215f83805a03781d116a...
500,Islam: A challenge to Christianity,"Pratt, Douglas",2007-05,religion,The coming together of people of diverse relig...,Islam: A challenge to Christianity The coming ...,e78b290de5806ec9cf4f1a11879608c0b6d120038242fb...

Authors: Siebel, Wolfgang
Abstract: The Acigöl rhyolite field erupted the most recent high-silica rhyolites within the Cappadocian Volca...

,title,authors,year,subjects,abstract,text,record_id_hash
4654,"Acigöl rhyolite field, central Anatolia (part ...","Siebel, Wolfgang",2011,Acigöl,The Acigöl rhyolite field erupted the most rec...,"Acigöl rhyolite field, central Anatolia (part ...",50be8ba0f4547e6e4dbce71a76adfb63e476d4af45155d...
9221,Zircon response to high-grade metamorphism as ...,"Siebel, Wolfgang",2012,Bohemian Massif,The Acigöl rhyolite field erupted the most rec...,Zircon response to high-grade metamorphism as ...,a1ec88398381af38477c8ae16396d7e1a5e09e90fdadd7...

Authors: Stokes, Evelyn
Abstract: A report providing a historical and geographical overview on the confiscation of Tauranga lands. In ...

,title,authors,year,subjects,abstract,text,record_id_hash
12738,Te Raupatu o Tauranga Moana = The confiscation...,"Stokes, Evelyn",1990,Tauranga lands,A report providing a historical and geographic...,Te Raupatu o Tauranga Moana = The confiscation...,439b3faa957f24108082ca860fd73be6ff3d5d4b7e0439...
2225,"Te Raupatu o Tauranga Moana : Volume 2, Docume...","Stokes, Evelyn",1993,Tauranga lands,A report providing a historical and geographic...,"Te Raupatu o Tauranga Moana : Volume 2, Docume...",7c21087a755c97474e40c8d4c22e25952f9eebc7d03e57...

Authors: Walmsley, Timothy Gordon
Abstract: Heat recovery from exhaust gas streams is applicable to a wide variety of industries. However, high ...

,title,authors,year,subjects,abstract,text,record_id_hash
4956,Numerical performance comparison of different ...,"Walmsley, Timothy Gordon",2012,heat recovery,Heat recovery from exhaust gas streams is appl...,Numerical performance comparison of different ...,3f1da394928958172d01dc804fba31acb5677a69267fe4...
2618,Numerical performance comparison of different ...,"Walmsley, Timothy Gordon",2012-08-27,NaN,Heat recovery from exhaust gas streams is appl...,Numerical performance comparison of different ...,107cf2850fbdeb0d9f30fb34a0e96ca2547b3bc436cfe3...

Authors: Walmsley, Timothy Gordon
Abstract: One method to reduce the energy consumption of industrial milk spray dryers is to recover waste heat...

,title,authors,year,subjects,abstract,text,record_id_hash
9509,An investigation of milk powder deposition on ...,"Walmsley, Timothy Gordon",2012-09-23,NaN,One method to reduce the energy consumption of...,An investigation of milk powder deposition on ...,c1d48ebc616f3314b345ddbbbbb0f2be55019bf2546a85...
8031,Fouling and pressure drop analysis of milk pow...,"Walmsley, Timothy Gordon",2013,fouling,One method to reduce the energy consumption of...,Fouling and pressure drop analysis of milk pow...,8b6770e0af5d440a08730c907f84c163812d4f21b0b432...

Authors: Wang, Hongyu
Abstract: Metaheuristic search algorithms are used to develop new protocols for optimal intravenous insulin in...

,title,authors,year,subjects,abstract,text,record_id_hash
12453,Metaheuristics for Discovering Favourable Cont...,"Wang, Hongyu",2020-01-01,Science & Technology,Metaheuristic search algorithms are used to de...,Metaheuristics for Discovering Favourable Cont...,55f432aa9fe33d8becfc831937d355731187872ade6f9c...
10214,Metaheuristic optimization of insulin infusion...,"Wang, Hongyu",2021,computer science,Metaheuristic search algorithms are used to de...,Metaheuristic optimization of insulin infusion...,e05d04c656a2bf6ed96d41800ec4f2845418572796b1ad...

### Step 8: Detailed Review of Records with Same Authors & Abstract but Different Years

Let's perform a detailed review of these 18 groups to understand the nature of their differences, especially concerning the 'title' and 'subjects' columns, before deciding on a merging or cleaning strategy. This will help us determine if they are revised versions of the same work or distinct publications.

In [ ]:
print('\n--- Detailed Examination of Records with Year Variations ---')

if not multi_year_entries_summary.empty:
    for index, row in multi_year_entries_summary.iterrows():
        authors = row['authors']
        abstract = row['abstract']

        print(f"\nGroup {index + 1}:")
        print(f"  Authors: {authors}")
        print(f"  Abstract (truncated): {abstract[:150]}...") # Display a longer abstract snippet

        # Filter and display relevant columns for comparison within this group
        display_cols = ['title', 'year', 'subjects']
        display(df_cleaned[
            (df_cleaned['authors'] == authors) &
            (df_cleaned['abstract'] == abstract)
        ][display_cols].sort_values(by='year'))
else:
    print("No records found with the same authors and abstract but different years for detailed examination.")

--- Detailed Examination of Records with Year Variations ---

Group 4623:
  Authors: Frank, Eibe
  Abstract (truncated): Bagging is an ensemble learning method that has proved to be a useful tool in the arsenal of machine learning practitioners. Commonly applied in conju...

,title,year,subjects
11621,Improving on bagging with input smearing,2006,computer science
11380,An Empirical Comparison of Exact Nearest Neigh...,2007,computer science

Group 4897:
  Authors: Ghaleiha, Amin
  Abstract (truncated): Becoming a father is a major transition for men, and may be a source of happiness and fulfilment, as well as distress. Perinatal mental health researc...

,title,year,subjects
9048,Fathers' Help Seeking and Support: The Importa...,2024,NaN
15421,Fathers’ help-seeking and support: The importa...,2024-03-25,Fatherhood

Group 5342:
  Authors: Groves, Lindsay
  Abstract (truncated): We report on the software development techniques used in the New Zealand software industry, paying particular attention to requirements gathering. We ...

,title,year,subjects
15837,A survey of software requirements specificatio...,1999-06,computer science
12580,A survey of software development practices in ...,2000-04,survey

Group 6452:
  Authors: Holmes, Mark J.
  Abstract (truncated): Markov regime-switching analysis is used to consider the relationship between business confidence and the probability of turning points in cyclical GD...

,title,year,subjects
5439,Business confidence and cyclical turning point...,2007-09,business confidence
13146,Business confidence and cyclical turning point...,2010,New Zealand

Group 7669:
  Authors: Khoo, Elaine G.L.
  Abstract (truncated): Developing online learning communities is a promising pedagogical approach in online learning contexts for adult tertiary learners, but it is no easy ...

                                                  title  year         subjects
4481  Evaluating an online learning community: Intel...  2011  online teaching
6412  Evaluating an online learning community: Intel...  2015  Online teaching

Group 8883:
  Authors: Lowe, David J.
  Abstract (truncated): New Zealand consists of a cluster of islands, the three largest being North, South, and Stewart, in the southwest Pacific Ocean. They have a total lan...

                                                   title        year subjects
13970                        Introduction to New Zealand        1994      NaN
7517   Intra-conference and Post-conference Tour Guid...  1994-02-01      NaN

Group 8900:
  Authors: Lowe, David J.
  Abstract (truncated): Tephras are fragmentary materials that are blasted explosively into the air during volcanic eruptions. Distributed throughout Zealandia, tephras provi...

,title,year,subjects
15571,Far-flung markers,2008,NaN
6027,Far-flown markers,2015,"tephras, tephrostratigraphy, tephrochronology,..."

Group 10263:
  Authors: Mohajerani, Sahar
  Abstract (truncated): In a previous paper we introduced the notion of synthesis abstraction, which allows efficient compositional synthesis of maximally permissive supervis...

,title,year,subjects
731,On the use of observation equivalence in synth...,2011,computer science
15964,Three variations of observation equivalence pr...,2011-01-26,computer science

Group 10834:
  Authors: Nichols, David M.
  Abstract (truncated): Open source communities have successfully developed many pieces of software although most computer users only use proprietary applications. The usabil...

,title,year,subjects
15950,Usability and open source software,2002-12-01,NaN
12915,The usability of open source software: analysi...,2006,computer science

Group 10844:
  Authors: Nichols, David M.
  Abstract (truncated): We describe a Web-based metadata quality tool that provides statistical descriptions and visualisations of Dublin Core metadata harvested via the OAI ...

                                     title     year          subjects
4314   A lightweight metadata quality tool     2008  computer science
15918         A tool for metadata analysis  2008-02       measurement

Group 10953:
  Authors: Nock, Sophie
  Abstract (truncated): Ko te whāinga matua o tēnei rangahau he whakakaokao, he wetewete āno hoki i ngā whakahokinga kōrero a te hunga uiui i kake atu ai ki runga i te waka o...

                                                   title     year   subjects
8181   He pūrongo whakahokinga kōrero a te akomanga r...  2012-05  Reo Māori
12469  Ko ngā whakahokinga kōrero a te hunga uiui i r...     2017  Reo Māori

Group 11787:
  Authors: Plimmer, Beryl
  Abstract (truncated): This demonstration shows the tool we have developed for hand-sketching user interfaces. Our motivation for developing this tool is to provide an envir...

                                                   title  year   subjects
1700   FreeForm: Informal form design on a large inte...  2001  Sketching
11155        Freeform: A Tool for Sketching Form Designs  2003  Sketching

Group 11937:
  Authors: Pratt, Douglas
  Abstract (truncated): The coming together of people of diverse religions to plan or reflect upon a common action or venture, and to consider, let alone engage in, an act of...

                                                 title     year  subjects
10260  Interreligious prayer: Prospects and parameters  2006-10  religion
500                 Islam: A challenge to Christianity  2007-05  religion

Group 13362:
  Authors: Siebel, Wolfgang
  Abstract (truncated): The Acigöl rhyolite field erupted the most recent high-silica rhyolites within the Cappadocian Volcanic Province of central Anatolia, Turkey. It compr...

                                                  title  year         subjects
4654  Acigöl rhyolite field, central Anatolia (part ...  2011           Acigöl
9221  Zircon response to high-grade metamorphism as ...  2012  Bohemian Massif

Group 13882:
  Authors: Stokes, Evelyn
  Abstract (truncated): A report providing a historical and geographical overview on the confiscation of Tauranga lands. In two volumes, volume one comprises a narrative of t...

                                                   title  year        subjects
12738  Te Raupatu o Tauranga Moana = The confiscation...  1990  Tauranga lands
2225   Te Raupatu o Tauranga Moana : Volume 2, Docume...  1993  Tauranga lands

Group 15163:
  Authors: Walmsley, Timothy Gordon
  Abstract (truncated): Heat recovery from exhaust gas streams is applicable to a wide variety of industries. However, high heat transfer resistance of gases and the presence...

,title,year,subjects
4956,Numerical performance comparison of different ...,2012,heat recovery
2618,Numerical performance comparison of different ...,2012-08-27,NaN

Group 15167:
  Authors: Walmsley, Timothy Gordon
  Abstract (truncated): One method to reduce the energy consumption of industrial milk spray dryers is to recover waste heat from the exhaust dryer air. A significant challen...

                                                  title        year subjects
9509  An investigation of milk powder deposition on ...  2012-09-23      NaN
8031  Fouling and pressure drop analysis of milk pow...        2013  fouling

Group 15213:
  Authors: Wang, Hongyu
  Abstract (truncated): Metaheuristic search algorithms are used to develop new protocols for optimal intravenous insulin infusion rate recommendations in scenarios involving...

,title,year,subjects
12453,Metaheuristics for Discovering Favourable Cont...,2020-01-01,Science & Technology
10214,Metaheuristic optimization of insulin infusion...,2021,computer science

In [ ]:
import difflib

print('\n--- Title Similarity Analysis for Multi-Year Groups ---')

if not multi_year_entries_summary.empty:
    for index, row in multi_year_entries_summary.iterrows():
        authors = row['authors']
        abstract = row['abstract']

        # Get all records for the current group
        group_records = df_cleaned[
            (df_cleaned['authors'] == authors) &
            (df_cleaned['abstract'] == abstract)
        ].sort_values(by='year').reset_index(drop=True)

        titles = group_records['title'].tolist()

        print(f"\nGroup {index + 1}: Authors: {authors}, Abstract: {abstract[:100]}...")
        print("  Titles:")
        for i, title in enumerate(titles):
            print(f"    [{i+1}] {title}")

        if len(titles) > 1:
            print("  Similarity Scores (Ratio):")
            # Calculate similarity for all unique pairs of titles
            for i in range(len(titles)):
                for j in range(i + 1, len(titles)):
                    title1 = titles[i]
                    title2 = titles[j]
                    similarity = difflib.SequenceMatcher(None, title1, title2).ratio()
                    print(f"    Title '{i+1}' vs Title '{j+1}': {similarity:.2f}")
        else:
            print("    (Only one title in this group, no similarity to calculate)")
else:
    print("No records found with the same authors and abstract but different years for similarity analysis.")

--- Title Similarity Analysis for Multi-Year Groups ---

Group 4623: Authors: Frank, Eibe, Abstract: Bagging is an ensemble learning method that has proved to be a useful tool in the arsenal of machine...
  Titles:
    [1] Improving on bagging with input smearing
    [2] An Empirical Comparison of Exact Nearest Neighbour Algorithms
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.28

Group 4897: Authors: Ghaleiha, Amin, Abstract: Becoming a father is a major transition for men, and may be a source of happiness and fulfilment, as...
  Titles:
    [1] Fathers' Help Seeking and Support: The Importance of Relationships for Mental Wellbeing
    [2] Fathers’ help-seeking and support: The importance of relationships for mental wellbeing
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.90

Group 5342: Authors: Groves, Lindsay, Abstract: We report on the software development techniques used in the New Zealand software industry, paying p...
  Titles:
    [1] A survey of software requirements specification practices in the New Zealand software industry
    [2] A survey of software development practices in the New Zealand software industry
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.86

Group 6452: Authors: Holmes, Mark J., Abstract: Markov regime-switching analysis is used to consider the relationship between business confidence an...
  Titles:
    [1] Business confidence and cyclical turning points: A Markov-Switching approach
    [2] Business confidence and cyclical turning points: a Markov-switching approach
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.97

Group 7669: Authors: Khoo, Elaine G.L., Abstract: Developing online learning communities is a promising pedagogical approach in online learning contex...
  Titles:
    [1] Evaluating an online learning community: Intellectual, social and emotional development and transformations.
    [2] Evaluating an online learning community: Intellectual, social and emotional development and transformations
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 1.00

Group 8883: Authors: Lowe, David J., Abstract: New Zealand consists of a cluster of islands, the three largest being North, South, and Stewart, in ...
  Titles:
    [1] Introduction to New Zealand
    [2] Intra-conference and Post-conference Tour Guides, International Inter-INQUA Field Conference and Workshop on Tephrochronology, Loess, and Paleopedology
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.18

Group 8900: Authors: Lowe, David J., Abstract: Tephras are fragmentary materials that are blasted explosively into the air during volcanic eruption...
  Titles:
    [1] Far-flung markers
    [2] Far-flown markers
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.88

Group 10263: Authors: Mohajerani, Sahar, Abstract: In a previous paper we introduced the notion of synthesis abstraction, which allows efficient compos...
  Titles:
    [1] On the use of observation equivalence in synthesis abstraction
    [2] Three variations of observation equivalence preserving synthesis abstraction
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.81

Group 10834: Authors: Nichols, David M., Abstract: Open source communities have successfully developed many pieces of software although most computer u...
  Titles:
    [1] Usability and open source software
    [2] The usability of open source software: analysis and prospects
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.63

Group 10844: Authors: Nichols, David M., Abstract: We describe a Web-based metadata quality tool that provides statistical descriptions and visualisati...
  Titles:
    [1] A lightweight metadata quality tool
    [2] A tool for metadata analysis
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.51

Group 10953: Authors: Nock, Sophie, Abstract: Ko te whāinga matua o tēnei rangahau he whakakaokao, he wetewete āno hoki i ngā whakahokinga kōrero ...
  Titles:
    [1] He pūrongo whakahokinga kōrero a te akomanga rūmaki o Te Tohu Paetahi
    [2] Ko ngā whakahokinga kōrero a te hunga uiui i roto i te akomanga rumaki i te Whare Wānanga o Waikato: He pūrongo mō ngā ui pātai
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.55

Group 11787: Authors: Plimmer, Beryl, Abstract: This demonstration shows the tool we have developed for hand-sketching user interfaces. Our motivati...
  Titles:
    [1] FreeForm: Informal form design on a large interactive display surface
    [2] Freeform: A Tool for Sketching Form Designs
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.41

Group 11937: Authors: Pratt, Douglas, Abstract: The coming together of people of diverse religions to plan or reflect upon a common action or ventur...
  Titles:
    [1] Interreligious prayer: Prospects and parameters
    [2] Islam: A challenge to Christianity
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.27

Group 13362: Authors: Siebel, Wolfgang, Abstract: The Acigöl rhyolite field erupted the most recent high-silica rhyolites within the Cappadocian Volca...
  Titles:
    [1] Acigöl rhyolite field, central Anatolia (part II): geochemical and isotopic (Sr–Nd–Pb, δ¹⁸O) constraints on volcanism involving two high-silica rhyolite suites
    [2] Zircon response to high-grade metamorphism as revealed by U–Pb and cathodoluminescence studies
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.26

Group 13882: Authors: Stokes, Evelyn, Abstract: A report providing a historical and geographical overview on the confiscation of Tauranga lands. In ...
  Titles:
    [1] Te Raupatu o Tauranga Moana = The confiscation of Tauranga lands. [Volume 1]
    [2] Te Raupatu o Tauranga Moana : Volume 2, Documents relating to tribal history, confiscation and reallocation of Tauranga lands.
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.61

Group 15163: Authors: Walmsley, Timothy Gordon, Abstract: Heat recovery from exhaust gas streams is applicable to a wide variety of industries. However, high ...
  Titles:
    [1] Numerical performance comparison of different tube cross–sections for heat recovery from particle-laden exhaust gas streams
    [2] Numerical performance comparison of different tube cross-sections for heat recovery from particle-laden exhaust gas streams
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.99

Group 15167: Authors: Walmsley, Timothy Gordon, Abstract: One method to reduce the energy consumption of industrial milk spray dryers is to recover waste heat...
  Titles:
    [1] An investigation of milk powder deposition on parallel fins
    [2] Fouling and pressure drop analysis of milk powder deposition on the front of parallel fins
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.64

Group 15213: Authors: Wang, Hongyu, Abstract: Metaheuristic search algorithms are used to develop new protocols for optimal intravenous insulin in...
  Titles:
    [1] Metaheuristics for Discovering Favourable Continuous Intravenous Insulin Rate Protocols from Historical Patient Data
    [2] Metaheuristic optimization of insulin infusion protocols using historical data with validation using a patient simulator
  Similarity Scores (Ratio):
    Title '1' vs Title '2': 0.49

### Step 9: Handling Missing Values - Dropping Rows with Nulls in Key Columns

To ensure data quality for subsequent analysis, we will remove rows that have missing values in the `authors`, `abstract`, or `year` columns. This creates a new DataFrame `df_final` with complete records for these critical fields.

In [ ]:
print('--- Dropping rows with null values in authors, abstract, or year ---')
df_final = df_cleaned.dropna(subset=['authors', 'abstract', 'year']).copy()

print('\n--- DataFrame Information after dropping rows with nulls ---')
df_final.info()

print('\n--- Checking for remaining missing values in authors, abstract, and year ---')
print(df_final[['authors', 'abstract', 'year']].isnull().sum())

--- Dropping rows with null values in authors, abstract, or year ---

--- DataFrame Information after dropping rows with nulls ---
<class 'pandas.core.frame.DataFrame'>
Index: 16590 entries, 0 to 16680
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           16590 non-null  object
 1   authors         16590 non-null  object
 2   year            16590 non-null  object
 3   subjects        11931 non-null  object
 4   abstract        16590 non-null  object
 5   text            16590 non-null  object
 6   record_id_hash  16590 non-null  object
dtypes: object(7)
memory usage: 1.0+ MB

--- Checking for remaining missing values in authors, abstract, and year ---
authors     0
abstract    0
year        0
dtype: int64

### Step 10: Re-checking for Duplicate Entries in `df_final`

Now that we've cleaned the `authors`, `abstract`, and `year` columns by dropping rows with null values, let's re-verify for duplicate entries based on the combination of `title`, `abstract`, `authors`, and `year` in our `df_final` DataFrame. This ensures data integrity after the cleaning process.

In [ ]:
print('\n--- Checking for duplicate entries in df_final based on \'title\', \'abstract\', \'authors\', and \'year\' ---')
duplicate_entries_final = df_final[df_final.duplicated(subset=['title', 'abstract', 'authors', 'year'], keep=False)]

if not duplicate_entries_final.empty:
    print(f"Found {len(duplicate_entries_final)} potential duplicate entries in df_final.")
    display(duplicate_entries_final.sort_values(by=['title', 'year']).head())
else:
    print("No duplicate entries found in df_final based on 'title', 'abstract', 'authors', and 'year'.")

--- Checking for duplicate entries in df_final based on 'title', 'abstract', 'authors', and 'year' ---
No duplicate entries found in df_final based on 'title', 'abstract', 'authors', and 'year'.

### Step 11: Save the Cleaned DataFrame to CSV

Now that we have cleaned the data and handled missing values and duplicates in key columns, let's save the `df_final` DataFrame to a new CSV file. This will allow us to easily reuse the cleaned dataset for further analysis.

In [ ]:
num_rows = df_final.shape[0]
output_csv_path = f'/content/drive/MyDrive/NZ/University of Waikato/Māori Data Findability Project/stage2_colab/Datasets/6_cleaned_hashed_dataset_{num_rows}.csv'

try:
    df_final.to_csv(output_csv_path, index=False)
    print(f"Successfully saved the cleaned DataFrame to '{output_csv_path}'")
except Exception as e:
    print(f"An error occurred while saving the DataFrame: {e}")

Successfully saved the cleaned DataFrame to '/content/drive/MyDrive/NZ/University of Waikato/Māori Data Findability Project/stage2_colab/Datasets/6_cleaned_hashed_dataset_16590.csv'